services:
  ntra-web:
    container_name: ntra-web
    image: nginx:alpine
    ports:
      - "9090:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ntra-app
    networks:
      - ntra-network

  ntra-app:
    container_name: ntra-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - ntra-postgres
    volumes:
      - ./:/var/www
    networks:
      - ntra-network

  ntra-postgres:
    image: postgres
    container_name: ntra-postgres
    restart: always
    expose:
      - 5432
    ports:
      - "2345:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ntra_postgres_data:/var/lib/postgresql/data
    networks:
      - ntra-network

  ntra-pgadmin:
    image: dpage/pgadmin4
    container_name: ntra-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8000:80"
    networks:
      - ntra-network

  ntra-node:
    image: node:22
    container_name: ntra-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    tty: true
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - ntra-network

networks:
  ntra-network:
    driver: bridge

volumes:
  ntra_postgres_data:
